PathoLab.Web/Controllers/PathoLabController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using PathoLab.Domain.PathoBilMasterl;
using PathoLab.Domain.PrescriptionMaster;
using PathoLab.IRepository.Account;
using PathoLab.IRepository.DignosisConfigurationMaster;
using PathoLab.IRepository.DignosisMaster;
using PathoLab.IRepository.DoctorMaster;
using PathoLab.IRepository.LabTestMaster;
using PathoLab.IRepository.PathoBillMaster;
using PathoLab.IRepository.PrescriptionMaster;
using PathoLab.IRepository.UserRegistration;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
//using IronBarCode;
using System.Text;
using System.Threading.Tasks;
using System.Drawing.Imaging;
using iTextSharp.text.pdf;
using Serilog;

namespace PathoLab.Web.Controllers
{
    public class PathoLabController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;
        private IPathoBillRepository _pathoBill;
        private IUser _user;
        private IDignosisConfigurationRepository _dignosisConfiguration;
        private ILabtest _labtest;

        public IConfiguration Configuration { get; }
        public PathoLabController(IHostingEnvironment hostingEnvironment, IConfiguration configuration, IPathoBillRepository pathoBill, IUser user, IDignosisConfigurationRepository dignosisConfiguration, ILabtest labtest)
        {
            _hostingEnvironment = hostingEnvironment;
            _pathoBill = pathoBill;
            _user = user;
            _dignosisConfiguration = dignosisConfiguration;
            _labtest = labtest;
        }

        public async Task<IActionResult> PathoLabBill()//Patho Lab Bill
        {
            Log.Information("PathoLabBill Started");
            var UserId = HttpContext.Session.GetInt32("UserId");
            if (!string.IsNullOrEmpty(UserId.ToString()))
            {
                ViewBag.ReportedOn = _pathoBill.BindCurrentDate().Result.ReportedOn;
                ViewBag.CollectionId = _pathoBill.BindCollection().Result.CollectionId;
                ViewBag.DoctorName = _user.DoctorDDL().Result;// DropDown (Fill Doctor name)
                //string otp = GetRandomText();//Auto Generate 10 digit code
                //ViewBag.no = otp;//Auto Generate 10 digit code
                return View();
            }
            else
            {
                return RedirectToAction("Logout", "Account");
            }
        }


        [HttpPost]
        public async Task<JsonResult> InsertPathoBill(PathoBill entity)//insert patho lab bill
        {
            Log.Information("InsertPathoBill ");
            try
            {
                //entity.Barcode = generateBarcode();
                int retMsg = _pathoBill.InsertPathoBill(entity).Result;//retMsg-Carry PathoBillId
                if (retMsg != 0)
                {

                    int retMsgPM = 0;//PrescribeMedicineId
                    if (entity.Tests != null)
                    {
                        foreach (var test in entity.Tests)
                        {
                            if (test.LabTestId != 0)
                            {
                                test.PathoBillId = retMsg;
                                retMsgPM = _pathoBill.InsertingTestFields(test).Result;
                            }

                        }
                    }
                    return Json("PathoBill Saved Successfully");
                }

                else
                {
                    return Json("Some Error Occurs");
                }

            }
            catch (Exception ex)
            {
                Log.Error(ex.Message + "\n" + ex.StackTrace);
                throw ex;
            }
        }
        public async Task<JsonResult> InsertPathoReportCollection(PathoBill entity)//insert patho report Collection
        {
            Log.Information("InsertPathoReportCollection ");
            try
            {
                int retMsgg = 1;
                //int retMsgg = _pathoBill.UploadFileByBillAndLabTestId(entity).Result;//retMsg-Carry PathoBillId
                int retMsg = _pathoBill.DeleteToUpdateReportCollection(entity.PathoBillId, entity.LabTestId).Result;//retMsg-Carry PathoBillId
                if (retMsgg != 0 && retMsg != 0)
                {
                    int retMsgPM = 0;
                    if (entity.TestValues != null)
                    {
                        foreach (var value in entity.TestValues)
                        {
                            if (value.DignosisConfigId != 0)
                            {
                                retMsgPM = _pathoBill.InsertPathoReportCollection(value).Result;
                            }

                        }
                    }
                    return Json("PathoLab Record Saved Successfully");
                }
                else
                {
                    return Json("Some Error Occurs");
                }

            }
            catch (Exception ex)
            {
                Log.Error(ex.Message + "\n" + ex.StackTrace);
                throw ex;
            }

        }
        public async Task<IActionResult> PathoReportCollectionForPrint()//Patho Report View Page Before Print
        {
            Log.Information("Patho Report Collection For Print ");
            ViewBag.Result = await _pathoBill.GetAllPathoBillRecord(new PathoBill());
            return View();
        }
        
        public async Task<IActionResult> ViewPathoLabCollection()// Patho Report Collection  View Page
        {
            Log.Information("View PathoLab Collection ");
            ViewBag.Result = await _pathoBill.GetAllPathoBill(new PathoBill());
            return View();
        }
        public async Task<IActionResult> ViewsPathoLabReport()
        {
            Log.Information(" Views PathoLab Report  ");
            return View();
        }
        public async Task<IActionResult> CollectSample(int PathoBillId)//  Sample Collection  View Page
        {
            Log.Information(" Collect Sample  ");
            var pathobill = _pathoBill.GetPatientDetailsByPathoBillId(Convert.ToInt32(PathoBillId),0).Result;
            return View();
        }
        [HttpPost]
        public async Task<JsonResult> SampleCollectionInfo(PathoBill entity)
        {
            Log.Information(" Sample Collection Information");
            try
            {
                int retMsg = _pathoBill.CreateInfo(entity).Result;
                if (retMsg != 0)
                {
                    int retMsgPM = 0;
                    if (entity.CollectionSample != null)
                    {
                        foreach(var samplecol in entity.CollectionSample)
                        {
                            if (samplecol.LabTestId != 0)
                            {
                                samplecol.SampleColNo = retMsg;
                                samplecol.PathoBillId = entity.PathoBillId;
                                retMsgPM = _pathoBill.CreateSample(samplecol).Result;
                            }
                        }
                    }
                    return Json("Data Saved Successfully");
                }
                else
                {
                    return Json("Some Error Occurs");
                }


            }
            catch (Exception ex)
            {
                Log.Error(ex.Message + "\n" + ex.StackTrace);
                throw ex;
            }
        }
        public async Task<IActionResult> PrintBill()
        {
            Log.Information(" Print Bill");
            return View();
        }
        [HttpGet]
        public IActionResult PrintPathoBill(int PathoBillId)
        {
            Log.Information(" Print Patho Bill");
            var pathobill = _pathoBill.GetPatientDetailsByPathoBillId(Convert.ToInt32(PathoBillId),0).Result;
            return Ok(JsonConvert.SerializeObject(pathobill));
        }
        public async Task<IActionResult> PrintReport()
        {
            Log.Information(" Print Report");
            return View();
        }
        [HttpGet]
        public IActionResult PrintPathoReport(int PathoBillId)
        {
            Log.Information(" Print Patho Report");
            var pathobill = _pathoBill.GetPatientDetailsByPathoBillId(Convert.ToInt32(PathoBillId),0).Result;
            return Ok(JsonConvert.SerializeObject(pathobill));
        }
        [HttpGet]
        public IActionResult BindingTest(int PathoBillId)
        {
            Log.Information(" Binding Test");
            var pathobill = _pathoBill.BindingTest(Convert.ToInt32(PathoBillId)).Result;
            return Ok(JsonConvert.SerializeObject(pathobill));
        }

        //Get Patient Details By PathoBillId
        [HttpGet]
        public IActionResult GetPatientDetailsByPathoBillId(int PathoBillId,int LabTestId)
        {
            Log.Information(" Get Patient Details By Patho Bill Id");
            var result = _pathoBill.GetPatientDetailsByPathoBillId(Convert.ToInt32(PathoBillId), LabTestId).Result;
            return Ok(JsonConvert.SerializeObject(result));
        }
        [HttpGet]
        public IActionResult BindingTestConfig(int PathoBillId)
        {
            Log.Information(" Binding Test Config");
            var pathobill = _pathoBill.BindingTestConfig(Convert.ToInt32(PathoBillId)).Result;
            return Ok(JsonConvert.SerializeObject(pathobill));
        }

        [HttpGet]
        public IActionResult GetPatientByMobile(string Mobile)
        {
            Log.Information(" Get Patient By Mobile");
            var Doctors = _pathoBill.GetPatientByMobile(Mobile).Result;
            return Ok(JsonConvert.SerializeObject(Doctors));
        }
        //Code For AutoFill Test Name
        [HttpPost]
        public JsonResult AutoComplete(string prefix)

PathoLab.Web/Views/PathoLab/CollectSample.cshtml
@{
    ViewData["Title"] = "CollectSample";
    Layout = "~/Views/Shared/_LayoutDynamic.cshtml";
    var ResultData = ViewBag.Result as List<PathoLab.Domain.PathoBilMasterl.PathoBill>;
}

<h2>Collect Sample</h2>
<link href="~/css/printprescription.css" rel="stylesheet" />

<div class="page-title">
    <div class="title-details">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb p-0 mb-0 bg-transparent" id="navigation">
            </ol>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs nav-fill" role="tablist">
                    <a class="nav-item nav-link  " asp-controller="PathoLab" asp-action="ViewCollection">Collection Page</a>
                    <a class="nav-item nav-link  active " asp-controller="PathoLab" asp-action="CollectSample"> Sample Collection</a>
                </ul>
                <div class="indicatorslist">
                    <a title="" href="javascript:void(0)" id="backIcon" data-toggle="tooltip" data-placement="top" data-original-title="Back"><i class="icon-arrow-left1"></i></a>
                    <p class="ml-2">(*) Indicates mandatory </p>
                </div>
            </div>
            <!--===================================================-->
            <!-- BASIC FORM ELEMENTS 1 -->
            <!--===================================================-->
            <h4>Patient Details</h4>
            <div class="card-body">
                <input type="hidden" id="hdnPathoBillId" class="form-control m-input">
                <input type="hidden" id="hdnCollectionId" class="form-control m-input">
                <div class="form-group row">
                    <div class="col-xs-12 col-md-2 col-xl-2">
                        <label class="control-label"><b>Name:-</b></label>
                        <label id="lblName"></label>
                    </div>
                    <div class="col-xs-12 col-md-3 col-xl-3">
                        <label class="control-label"><b>MobileNo:-</b> </label>
                        <label id="lblMobile"></label>
                    </div>
                    <div class="col-xs-12 col-md-1 col-xl-1">
                        <label class="control-label"><b>Age:-</b> </label>
                        <label id="lblAge"></label>
                    </div>
                    <div class="col-xs-12 col-md-2 col-xl-2">
                        <label class="control-label"><b>Gender:-</b></label>
                        <label id="lblGender"></label><br />
                    </div>
                    <div class="col-xs-12 col-md-3 col-xl-3">
                        <label class="control-label"><b>Email:-</b></label>
                        <label id="lblEmail"></label><br />
                    </div>
                </div>
            </div>


            <!--===================================================-->
            <!-- END BASIC FORM ELEMENTS 1-->
            <!--==============================================================================================================================================-->
            <!-- BASIC FORM ELEMENTS 2 -->
            <!--===================================================-->
            <div class="card-body">
                <div class="form-group row">
                    <div class="col-12 col-md-12 col-xl-12">
                        <div>
                            <table id="tblTestBill" class="col-12 col-md-12 col-xl-12">
                                <tr>
                                    <td><b>Sl#</b></td>
                                    <td><b>Test Name</b></td>
                                    <td><b>BarCodeNo</b></td>
                                    @*<td><b>Action</b></td>*@
                                </tr>
                                <tbody id="tbody"></tbody>

                            </table><br />
                        </div><br />
                    </div>
                </div>

                <!--==============================================================================================================================================-->

                <div class="form-group row">
                    <label class="col-12 col-md-2 col-xl-2 control-label"></label>
                    <div class="col-12 col-md-4 col-xl-4" style="margin-left:300px">
                        <button class="btn btn-primary mb-1" id="btnSubmit">Submit</button>
                    </div>
                </div>

                <!--==============================================================================================================================================-->
                <!-- END BASIC FORM ELEMENTS 2 -->
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        //breadcumb
        var PathoBillId = getUrlVars()["PathoBillId"];
        if (PathoBillId != undefined) {
            Collect(PathoBillId);
            Report(PathoBillId);
            Barcode(PathoBillId);
        }

    });
    var PathoBillIdTemp;
    var CollectionIdTemp;
    //DataBind From PathoLabCollection Table
    function Collect(PathoBillId) {
        $.ajax({
            url: "/PathoLab/GetPatientDetailsByPathoBillId?PathoBillId=" + PathoBillId,
            typr: "GET",
            contentType: "application/json;charset=UTF-8",
            dataType: "json",
            success: function (result) {
                $('#hdnPathoBillId').text(result.PathoBillId);
                PathoBillIdTemp = result.PathoBillId;
                CollectionIdTemp = result.CollectionId;
                $('#hdnCollectionId').text(result.CollectionId);
                $('#lblName').text(result.FullName);
                $('#lblDate').text(result.DateOfAppointment);
                $('#lblAge').text(result.Age);
                $('#lblGender').text(result.Gender);
                $('#lblMobile').text(result.Mobile);
                $('#lblEmail').text(result.Email);
                $('#lblLabTestMethodology').text(result.LabTestName);
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        });
    }

    //< !--=================================================== -->
    function Barcode(PathoBillId) {
        $.ajax({
            url: "/PathoLab/GetBarcodeByPathoBillId?PathoBillId=" + PathoBillId,
            typr: "GET",
            contentType: "application/json;charset=UTF-8",
            dataType: "json",
            success: function (data) {
                $("#divBarcode").html("<img style='height:50px;width:200px' src='" + JSON.parse(data).BarcodeImage + "' alt='' />");
            },
            //error: function (errormessage) {
            //    alert(errormessage.responseText);
            //}
        });
    }
    //< !--=================================================== -->

    function Report(PathoBillId) {
        $.ajax({
            url: "/PathoLab/BindingTest?PathoBillId=" + PathoBillId,
            typr: "GET",
            contentType: "application/json;charset=UTF-8",
            dataType: "json",
            success: function (data) {
                // Denotes total number of rows
                var rowIdx = "";
                // Adding a row inside the tbody.
                $.each(data, function (i, item) {
                    $('#tbody').append(`<tr id="R${++rowIdx}">
                      <td class="row-index text-center">
                     <label  class="control-label">${rowIdx}</label>
                    </td>
                     <td class="row-index text-center">
                     <label id="txtTestName"  class="control-label">${item.LabTestName}</label>
                    <input type="hidden" value="${item.LabTestId}" id="hdnLabTestId" class="form-control m-input">
                    </td>
                     <td class="row-index text-center">
                  <input id="txtBarcode" type="text" maxlength = "100" size = "10"class="form-control m-input" >
                 </td>

                    </tr>`
                    );
                });
            },
            //error: function (errormessage) {
            //    alert(errormessage.responseText);
            //}
        });
        // jQuery button click event to remove a row.
        $('#tbody').on('click', '.remove', function () {

            // Getting all the rows next to the row
            // containing the clicked button
            var child = $(this).closest('tr').nextAll();

            // Iterating across all the rows
            // obtained to change the index
            child.each(function () {
                // Getting <tr> id.
                var id = $(this).attr('id');
                // Getting the <p> inside the .row-index class.
                var idx = $(this).children('.row-index').children('p');
                // Gets the row number from <tr> id.
                var dig = parseInt(id.substring(1));
                // Modifying row index.
                idx.html(`Row ${dig - 1}`);
                // Modifying row id.
                $(this).attr('id', `R${dig - 1}`);
            });

            // Removing the current row.
            $(this).closest('tr').remove();

            // Decreasing total number of rows by 1.
            rowIdx--;
        });
    }
    //< !--=================================================== -->
    //Create
    $("#btnSubmit").click(function () {
        var selected = [];
        $('#newinput option:selected').each(function () {
            selected.push($(this).attr('value'));
        });
        // Array of data we'll retu
        var Items = []; //array declaring to store the records to send it to controller
        var entity = {};
        var tbl = document.getElementById('tbody');
        for (var i = 0; i < tbl.rows.length; i++) {
            var item1 = {};
            item1.LabTestId = tbl.rows[i].children[1].children[1].value;
            item1.Barcode = tbl.rows[i].children[2].children[0].value;
            Items.push(item1);
        }
        entity.CollectionSample = Items;
        
        entity.PathoBillId = PathoBillIdTemp;
        entity.CollectionId = CollectionIdTemp;
        debugger
        if (confirm("Are you sure you want to Submit ?")) {
            $.ajax({
                url: "/PathoLab/SampleCollectionInfo",
                data: entity,
                type: "POST",
                success: function (result) {
                    if (result = "Data Saved Successfully") {
                        alert(result);

                        location.href = "/PathoLab/ViewCollection";
                    }
                    else {
                        alert(result);
                        reset();
                    }
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }
            });
        }
    });

</script>

PathoLab.Web/Views/PathoLab/PathoReportCollectionForPrint.cshtml
@{
    ViewData["Title"] = "PathoReportCollectionForPrint";
    Layout = "~/Views/Shared/_LayoutDynamic.cshtml";
    var ResultData = ViewBag.Result as List<PathoLab.Domain.PathoBilMasterl.PathoBill>;
}


<div class="page-title">
    <div class="title-details">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb p-0 mb-0 bg-transparent" id="navigation">
            </ol>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs nav-fill" role="tablist">
                    @*<a class="nav-item nav-link   " asp-controller="PathoLab" asp-action="ViewsPathoLabReport"> Patho Lab Report</a>*@
                    <a class="nav-item nav-link active  " asp-controller="PathoLab" asp-action="PathoReportCollectionForPrint">View Patho Report</a>
                    <a class="nav-item nav-link   " asp-controller="PathoLab" asp-action="PrintReport"> Print Report</a>
                </ul>
                
            </div>
            <div class="card-body ">
                @if (ResultData != null && ResultData.ToList().Count > 0)
                {
                    <div class="table-responsive">
                        <table data-toggle="table" id="tblPathoBill" class="table">
                            <thead>
                                <tr>
                                    <th width="60px" class="align-top text-center">
                                        Sl#
                                    </th>
                                    <th width="150px" class="align-top">
                                        Collection Id
                                    </th>
                                    <th width="150px" class="align-top">
                                        PatientName
                                    </th>
                                    <th width="150px" class="align-top">
                                        Email
                                    </th>
                                    <th width="150px" class="align-top">
                                        Reported On
                                    </th>
                                    <th width="150px" class="align-top">
                                        Mobile
                                    </th>
                                    <th width="150px" class="align-top">
                                        Age
                                    </th>
                                    <th width="150px" class="align-top">
                                        Gender
                                    </th>
                                    <th width="150px" class="align-top">
                                        TestName
                                    </th>
                                    <th width="150px" class="align-top">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    int count = 1;
                                }
                                @foreach (var list in ResultData)
                                {
                                <tr>
                                    <td class="text-center">@count</td>
                                    <td>
                                        @list.CollectionId
                                    </td>
                                    <td>
                                        @list.FullName
                                    </td>
                                    <td>
                                        @list.Email
                                    </td>
                                    <td>
                                        @list.DateOfAppointment
                                    </td>
                                    <td>
                                        @list.Mobile
                                    </td>
                                    <td>
                                        @list.Age
                                    </td>
                                    <td>
                                        @list.Gender
                                    </td>
                                    <td>
                                        @list.LabTestName
                                    </td>
                                    <td>
                                        <a onclick="DeleteReport('@list.PathoBillId');" class="text-danger" title="" data-original-title="Delete"><i class="icon-trash-21"></i> <b>Delete</b></a><br />
                                        <a onclick="PrintReport('@list.PathoBillId');" class="text-primary mr-3" title="" data-original-title="Print"><i id="printprescription" class="fa fa-print" aria-hidden="true"></i> <b>Print</b></a><br />
                                    </td>

                                </tr>
                                    count++;
                                }
                            </tbody>
                        </table>
                    </div>
                }
                else
                {
                    <div class="norecord"> No Record Found</div>
                }
                <div class="clearfix col-sm-12"></div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        //breadcumb
        var PathoBillId = getUrlVars()["PathoBillId"];
        if (PathoBillId != undefined) {
            PrintReport(PathoBillId);
            DeleteReport(PathoBillId);
            getDataTable();
        }

    });

     //< !--=================================================== -->
    //Print Report
    function PrintReport(PathoBillId) {
        if (confirm("Are you sure you want to print ?")) {
            location.href = "/PathoLab/PrintReport?PathoBillId=" + PathoBillId ;

        }
    }

    $('icon').on('click', function () {
        PrintReport();
    })
    //< !--=================================================== -->


    //Delete Collect Report
    function DeleteReport(PathoBillId) {
        if (confirm("Are you sure you want to delete ?")) {
            $.ajax({
                url: "/PathoLab/DeletePathoBill?PathoBillId=" + PathoBillId,
                type: "POST",
                dataType: "json",
                contentType: "application/json;charset=UTF-8",
                success: function (data) {
                    if (data == "3") {
                        alert("PathoBill Report Deleted Successfully");
                        window.location.reload();
                    }
                    else if (data == "4") {
                        alert("PathoBill  Report Already In Use!");
                        window.location.reload();
                    }
                    else { }
                },
                error: function (error) {
                    jsonValue = jQuery.parseJSON(error.responseText);
                    bootbox.alert("Error : " + jsonValue);
                }
            });
        }
    }
    //< !--=================================================== -->
    //Pagination
    function getDataTable() {
        $('#tblPathoBill').DataTable({
            "searching": true,
            //"bStateSave": true,
            "dom": 'Bfrtip',
            "autoWidth": false,
            "buttons": [
                //{
                //    extend: 'print',
                //    title: 'Manage Block',
                //    exportOptions: {
                //        columns: [0, 1, 2, 3, 4]
                //    },
                //    customize: function (win) { $(win.document.body).css('font-size', '10pt').prepend('<img src="' + origin + '/images/t5-logo-white.png"  style="position:absolute; top:0; left:0;" />'); $(win.document.body).find('table').addClass('compact').css('font-size', 'inherit'); }

                //}
                ,
                {
                    extend: 'pageLength'
                }
            ],
            "lengthMenu": [
                [10, 25, 50, 100, 1000 - 1],
                ['10 rows', '25 rows', '50 rows', '100 rows', '1000 rows', 'Show all']
            ]
        });
    }
</script>