PathoLab.Web/Controllers/DignosisController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using PathoLab.Domain.DignosisMaster;
using PathoLab.IRepository.DignosisMaster;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace PathoLab.Web.Controllers
{
    public class DignosisController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;
        private readonly IDignosisRepository _dignosisRepository;
        public IConfiguration Configuration { get; }
        public DignosisController(IHostingEnvironment hostingEnvironment, IDignosisRepository dignosisRepository, IConfiguration configuration)
        {
            _hostingEnvironment = hostingEnvironment;
            Configuration = configuration;
            _dignosisRepository = dignosisRepository;
        }
        public async Task<IActionResult> AddDignosis()
        {
            List<Dignosis> pc4 = new List<Dignosis>();
            pc4 = await _dignosisRepository.BindDignosisCatagoryName(new Dignosis());
            pc4.Insert(0, new Dignosis { DignosisCatagoryID = 0, DignosisCategoryName = "Select" });
            ViewBag.Catagory = pc4;
            //var UserId = HttpContext.Session.GetInt32("UserId");
            //if (!string.IsNullOrEmpty(UserId.ToString()))
            //{
            return View();
            //}
            //else
            //{
            //    return RedirectToAction("Logout", "Account");
            //}
        }
        public async Task<IActionResult> ViewDignosis()
        {
            //var UserId = HttpContext.Session.GetInt32("UserId");
            //if (!string.IsNullOrEmpty(UserId.ToString()))
            //{
            List<Dignosis> pc4 = new List<Dignosis>();
            pc4 = await _dignosisRepository.BindDignosisCatagoryName(new Dignosis());
            pc4.Insert(0, new Dignosis { DignosisCatagoryID = 0, DignosisCategoryName = "Select" });
            ViewBag.Catagory = pc4;
            List<Dignosis> dl = new List<Dignosis>();
            List<Dignosis> dle = new List<Dignosis>();
            dl = await _dignosisRepository.GetAll(new Dignosis());
            foreach(Dignosis d in dl)
            {
                d.EncodDignosisID =  Encrypt(d.DignosisID.ToString());
                dle.Add(d);
            }
            
            // ViewBag.Result = await _dignosisRepository.GetAll(new Dignosis());
            ViewBag.Result = dle;

            return View();
            //}
            //else
            //{
            //    return RedirectToAction("Logout", "Account");
            //}
            
        }
     
        [HttpPost]

        public async Task<IActionResult> ViewDignosis(Dignosis d)

        {
            //var UserId = HttpContext.Session.GetInt32("UserId");
            //if (!string.IsNullOrEmpty(UserId.ToString()))
            //{
            List<Dignosis> pc4 = new List<Dignosis>();
            pc4 = await _dignosisRepository.BindDignosisCatagoryName(new Dignosis());
            pc4.Insert(0, new Dignosis { DignosisCatagoryID = 0, DignosisCategoryName = "Select" });
            ViewBag.Catagory = pc4;
           

            ViewBag.Result = await _dignosisRepository.GetAll(d);
            return View();
            //}
            //else
            //{
            //    return RedirectToAction("Logout", "Account");
            //}

        }
        [HttpPost]
        public async Task<JsonResult> AddDignosis(Dignosis entity)
        {
            try
            {
              
             
                 if ((!Regex.IsMatch(entity.Name, @"^[A-Za-z\s]{1,}[\.]{0,1}[A-Za-z\s]{0,}$")))
                {
                    return Json("Name  Is  Invalid");
                }
                else
                {
                    int retMsg = _dignosisRepository.Create(entity).Result;

                    if (retMsg == 1)
                    {
                        return Json("Record Saved Successfully");
                    }
                    else if (retMsg == 2)
                    {
                        return Json("Record Updated Successfully");
                    }
                    else
                    {
                        return Json("Record Already Exist");
                    }
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        [HttpPost]
        public IActionResult DeleteDignosis(int DignosisID)
        {
            try
            {
                int Result = _dignosisRepository.Delete(DignosisID).Result;
                return Json(Result);
            }
            catch (Exception Ex)
            {
                throw Ex;
            }
        }
        [HttpGet]
        public IActionResult DignosisGetById(string DignosisID)
        {
            var id = DignosisID + "=";
            int DignosisIDD = Convert.ToInt32(Decrypt(id));
            var Dignosiss = _dignosisRepository.GetOne(Convert.ToInt32(DignosisIDD)).Result;
            return Ok(JsonConvert.SerializeObject(Dignosiss));
        }

        public string Encrypt(string strToDecrypt)
        {
            string key = "C#S@$R%!";
            byte[] inputByptArr;
            byte[] keyBytes;
            string strToEncrypt;
            if (string.IsNullOrWhiteSpace(strToDecrypt))
            {
                strToEncrypt = null;
            }
            else
            {
                try
                {
                    inputByptArr = ASCIIEncoding.ASCII.GetBytes(strToDecrypt);
                    keyBytes = ASCIIEncoding.ASCII.GetBytes(key);

                    DESCryptoServiceProvider provider = new DESCryptoServiceProvider();
                    ICryptoTransform transform = provider.CreateEncryptor(keyBytes, keyBytes);
                    CryptoStreamMode mode = CryptoStreamMode.Write;

                    MemoryStream memStream = new MemoryStream();
                    CryptoStream cryptoStream = new CryptoStream(memStream, transform, mode);
                    cryptoStream.Write(inputByptArr, 0, inputByptArr.Length);
                    cryptoStream.FlushFinalBlock();

                    byte[] encryptedInputByteArr = new byte[memStream.Length];
                    memStream.Position = 0;
                    memStream.Read(encryptedInputByteArr, 0, encryptedInputByteArr.Length);

                    strToEncrypt = Convert.ToBase64String(encryptedInputByteArr).Replace('/', '_').Replace('+', '-');
                }
                catch (Exception ex)
                {
                    throw ex;
                }

            }
            return strToEncrypt;
        }
        public string Decrypt(string strToEncrypt)
        {
            string key = "C#S@$R%!";
            byte[] encryptedInputByteArr;
            byte[] keyBytes;
            string decryptedMsg;
            if (string.IsNullOrWhiteSpace(strToEncrypt))
            {
                decryptedMsg = null;
            }
            else
            {
                try
                {
                    //strToEncrypt = strToEncrypt.Trim();
                    strToEncrypt = strToEncrypt.Replace('-', '+').Replace('_', '/');
                    byte[] data = Encoding.UTF8.GetBytes(strToEncrypt);
                    encryptedInputByteArr = Convert.FromBase64String(strToEncrypt);
                    keyBytes = ASCIIEncoding.ASCII.GetBytes(key);

                    DESCryptoServiceProvider provider = new DESCryptoServiceProvider();
                    ICryptoTransform transform = provider.CreateDecryptor(keyBytes, keyBytes);
                    CryptoStreamMode mode = CryptoStreamMode.Write;

                    MemoryStream memStream = new MemoryStream();
                    CryptoStream cryptoStream = new CryptoStream(memStream, transform, mode);
                    cryptoStream.Write(encryptedInputByteArr, 0, encryptedInputByteArr.Length);
                    cryptoStream.FlushFinalBlock();

                    byte[] decryptedInputByteArr = new byte[memStream.Length];
                    memStream.Position = 0;
                    memStream.Read(decryptedInputByteArr, 0, decryptedInputByteArr.Length);

                    decryptedMsg = ASCIIEncoding.ASCII.GetString(decryptedInputByteArr);
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            return decryptedMsg;
        }

    }
}

PathoLab.Web/Views/Dignosis/AddDignosis.cshtml
@{
    ViewData["Title"] = "AddDignosis";
    Layout = "~/Views/Shared/_LayoutDynamic.cshtml";
}
<div class="page-title">
    <div class="title-details">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb p-0 mb-0 bg-transparent" id="navigation">
            </ol>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs nav-fill" role="tablist">
                    <a class="nav-item nav-link active" asp-controller="Dignosis" asp-action="AddDignosis">Add</a>
                    <a class="nav-item nav-link " asp-controller="Dignosis" asp-action="ViewDignosis">View</a>
                </ul>
                <div class="indicatorslist">
                    <a title="" href="javascript:void(0)" id="backIcon" data-toggle="tooltip" data-placement="top" data-original-title="Back"><i class="icon-arrow-left1"></i></a>
                    <p class="ml-2">(*) Indicates mandatory </p>
                </div>
            </div>
            <!-- BASIC FORM ELEMENTS -->
            <!--===================================================-->
            <div class="card-body">


                <!--Static-->

                <div class="form-group row">
                    <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input">Catagory  <span class="text-danger">*</span></label>
                    <div class="col-12 col-md-6 col-xl-4">
                        <select id="dnam" class="form-control" asp-items="@(new SelectList(ViewBag.Catagory,"DignosisCatagoryID","DignosisCategoryName"))">
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <input type="hidden" id="hdnDignosisID" />
                    <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input"> Name <span class="text-danger">*</span></label>
                    <div class="col-12 col-md-6 col-xl-4">
                        <input type="text" id="nam" class="form-control" onchange="Namevalidation('nam','lblErrorName')" />
                        <span id="lblErrorName" style="color:red"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-12 col-md-2 col-xl-2 control-label"></label>
                    <div class="col-12 col-md-6 col-xl-4">
                        <button class="btn btn-primary mb-1" id="btnSubmit">Submit</button>
                        <button class="btn btn-danger mb-1" id="btnReset">Reset</button>
                    </div>
                </div>


                <div class="modal fade" id="SubmitModal" tabindex="1" role="dialog"
                     aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5>Customer Details</h5>
                            </div>
                            <div class="modal-body">
                                <h6 class="modalMsg"></h6>
                            </div>
                            <div class="modal-footer">
                                <input type="submit" class="btn btn-info btn-sm submitConfirm hbtn" value="Yes" styk="display:none" />
                                <button type="button" class="btn btn-danger btn-sm No hbtn" data-dismiss="modal" aria-label="Close">No</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="SuccessModal" tabindex="1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="resultMsg" style="color:blue"></h5>
                            </div>
                            <div class="modal-body">
                                <h5 class="msgsuccess"></h5>
                            </div>
                            <div class="modal-footer">
                                <a class="btn btn-danger btnok" asp-controller="Dignosis" asp-action="ViewDignosis">Close</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="UnSuccessModal" tabindex="1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="resultMsg" style="color:blue"></h5>
                            </div>
                            <div class="modal-body">
                                <h5 class="msgunsuccess"></h5>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-danger btn-sm No hbtn" data-dismiss="modal" @*aria-label="Close"*@>Close</button>

                            </div>
                        </div>
                    </div>
                </div>

      
                <!--===================================================-->
                <!-- END BASIC FORM ELEMENTS -->
            </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        //breadcumb
        loadNavigation('Add Dignosis', 'gldata', 'plsubmission', 'Add Dignosis', '', 'Add Dignosis');
        var DignosisID = getUrlVars()["DignosisID"];
        if (DignosisID != undefined) {
            $("#btnSubmit").html("Update");
            $("#btnReset").html("Cancel");
            Edit(DignosisID);
        }
    });
    function validate() {

        if ($('#dnam').val() == "0") {
            $('.msgunsuccess').text('Please Select Catagory Name!');
            $('#UnSuccessModal').modal('show');

          // alert("Please Select Catagory Name!");
            $('#dnam').focus();
            return false;
          
        }
        else if ($('#nam').val() == "") {
            $('.msgunsuccess').text('Please Enter Name !');
            $('#UnSuccessModal').modal('show');

           // alert("Please Enter Name !");
            $('#nam').focus();
            return false;
          
        }
      
        else {
           // $("#btnReset").hide();
            return true;
        }

    }
    $("#btnReset").click(function () {
        if ($("#hdnDignosisID").val() != '') {
            window.location.href = "/Dignosis/ViewDignosis";
        }
        else
            reset();
    });
    $("#btnSubmit").click(function () {
        //var chkValidation = validate();
        if (validate() == true && Namevalidation('nam', 'lblErrorName') == true) {


          
                $('.modalMsg').text('Are you sure to save the details ?');
                $('.submitConfirm').css('display', 'block');
                $('#SubmitModal').modal("show");
            
           
        }
    });
    $(".submitConfirm").click(function () {
      

            var dign = {
                DignosisID: $("#hdnDignosisID").val(),
                Name: $("#nam").val(),
                DignosisCatagoryID: $("#dnam").val(),
               
            };
      
              
                $.ajax({
                    url: "/Dignosis/AddDignosis",
                    data: dign,
                    type: "POST",
                    success: function (result) {
                        if (result == "Record Saved Successfully") {
                            $('.modalMsg').text('');
                            $('#SubmitModal').modal("hide");
                            $('.msgsuccess').text('Data Saved successfully.');
                            $('#SuccessModal').modal('show');
                            reset()
                           

                        }
                        else if ((result == "Record Updated Successfully")) {
                            $('.modalMsg').text('');
                            $('#SubmitModal').modal("hide");
                            $('.msgsuccess').text('Data Updated successfully.');
                            $('#SuccessModal').modal('show');
                            //window.location.href = "/Dignosis/ViewDignosis";
                        }

                        else {
                            $('.modalMsg').text('');
                            $('#SubmitModal').modal("hide");
                            $('.msgunsuccess').text('Data Already Exits');
                            $('#UnSuccessModal').modal('show');
                        }
                    },
                    error: function (errormessage) {
                        alert(errormessage.responseText);
                    }
                });
           
       
    });
    //UPDATE
    function Edit(DignosisID) {


            $.ajax({
                url: "/Dignosis/DignosisGetById?DignosisID=" + DignosisID,
                typr: "GET",
                contentType: "application/json;charset=UTF-8",
                dataType: "json",
                success: function (result) {
                    $('#hdnDignosisID').val(result.DignosisID);
                    $("#nam").val(result.Name);
                    $("#dnam").val(result.DignosisCatagoryID);
                  
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }
            });
     
    }
    function reset() {
        $('#hdnDignosisID').val("");
        $("#nam").val("");
        $("#dnam").val("0");
    }

</script>

PathoLab.Web/Views/Dignosis/ViewDignosis.cshtml
@model PathoLab.Domain.DignosisMaster.Dignosis

@{
    ViewData["Title"] = "ViewDignosis";
    Layout = "~/Views/Shared/_LayoutDynamic.cshtml";
    var ResultData = ViewBag.Result as List<PathoLab.Domain.DignosisMaster.Dignosis>;

}
<div class="page-title">
    <div class="title-details">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb p-0 mb-0 bg-transparent" id="navigation">
            </ol>
        </nav>
    </div>

</div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs nav-fill" role="tablist">
                    <a class="nav-item nav-link" asp-controller="Dignosis" asp-action="AddDignosis">Add</a>
                    <a class="nav-item nav-link active" asp-controller="Dignosis" asp-action="ViewDignosis">View</a>
                </ul>
            </div>
            <!-- Search Panel-->
            <div class="search-container">
                <div class="search-sec" style="display: block;">
                    <form method="post" id="indsearch">
                        <div class="form-group form-row">
                            <div class="col-12 col-md-6 col-xl-3">
                                <label class="control-label"> Category</label>
                                <select id="Catid" class="form-control" asp-items="@(new SelectList(ViewBag.Catagory,"DignosisCatagoryID","DignosisCategoryName")) " asp-for="DignosisCatagoryID">
                                </select>
                            </div>
                            <div class="col-12 col-md-6 col-xl-3">
                                <label class="control-label"> Name</label>
                                <input class="form-control" id="txtName" asp-for="Name" />
                            </div>
                            <div class="col-lg-2 ">
                                <button id="btnSearch" class="btn btn-primary mt-xl-4 mt-2"> <i class="fa fa-search"></i> Search</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="text-center"> <a class="searchopen" title="Search" data-toggle="tooltip" data-placement="bottom"> <i class="icon-angle-arrow-down"></i> </a></div>
            </div>
            <!-- Search Panel -->
            <!--===================================================-->
            <div class="card-body ">
                @if (ResultData != null && ResultData.ToList().Count > 0)
                {
                    <div class="table-responsive">
                        <table data-toggle="table" id="tblDignosis" class="table">
                            <thead>
                                <tr>
                                    <th width="60px" class="align-top text-center">Sl#</th>
                                    <th width="150px" class="align-top">
                                        DignosisCategoryName
                                    </th>
                                    <th width="150px" class="align-top">
                                        Name
                                    </th>

                                    <th width="150px" class="align-top">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    int count = 1;
                                }
                                @foreach (var list in ResultData)
                                {
                                    <tr>
                                        <td class="text-center">@count</td>
                                        <td>
                                            @list.DignosisCategoryName
                                        </td>
                                        <td>
                                            @list.Name
                                        </td>

                                        <td>
                                            @*<a href="/Dignosis/AddDignosis?DignosisID=@Convert.ToString(list.DignosisID)" class="text-primary mr-3" title="" data-original-title="Edit"><i class="icon-edit1"></i></a>*@
                                            <a onclick="updateDepartment('@list.EncodDignosisID');" class="text-primary mr-3" title="" data-original-title="Edit"><i class="icon-edit1"></i><b>Edit</b></a><br />

                                            <a onclick="deleteDignosis('@list.DignosisID');" class="text-danger" title="" data-original-title="Delete"><i class="icon-trash-21"></i><b>Delete</b></a>
                                        </td>
                                    </tr>
                                    count++;
                                }
                            </tbody>
                        </table>
                    </div>
                }
                else
                {
                    <div class="norecord"> No Record Found</div>
                }
                <div class="clearfix col-sm-12"></div>
            </div>

            <div class="modal fade" id="SubmitModal" tabindex="1" role="dialog"
                 aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5>Customer Details</h5>
                        </div>
                        <div class="modal-body">
                            <h6 class="modalMsg"></h6>
                        </div>
                        <div class="modal-footer">
                            @*<a href="/RegistrationUser/User_Registration?id=@Convert.ToString(@list.UserId)" class="text-primary mr-3" title="" data-original-title="Edit"><i class="icon-edit1"></i></a>*@

                            <input type="submit" class="btn btn-info btn-sm submitConfirm hbtn" value="Yes" styk="display:none" />
                            <button type="button" class="btn btn-danger btn-sm No hbtn" data-dismiss="modal" aria-label="Close">No</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal fade" id="DSubmitModal" tabindex="1" role="dialog"
                 aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5>Customer Details</h5>
                        </div>
                        <div class="modal-body">
                            <h6 class="DmodalMsg"></h6>
                        </div>
                        <div class="modal-footer">
                            <input type="submit" class="btn btn-info btn-sm DsubmitConfirm hbtn" value="Yes" styk="display:none" />
                            <button type="button" class="btn btn-danger btn-sm No hbtn" data-dismiss="modal" aria-label="Close">No</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal fade" id="SuccessModal" tabindex="1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="resultMsg" style="color:blue"></h5>
                        </div>
                        <div class="modal-body">
                            <h5 class="msgsuccess"></h5>
                        </div>
                        <div class="modal-footer">
                            <a class="btn btn-danger btnok" asp-controller="Dignosis" asp-action="ViewDignosis">Close</a>
                        </div>
                    </div>
                </div>
            </div>
            <!--===================================================-->
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        getDataTable();
    })
    var x;
    function updateDepartment(DepartmentId) {
        $('.modalMsg').text('Are you sure to Update the details ?');
        $('.submitConfirm').css('display', 'block');
        $('#SubmitModal').modal("show");
        x = DepartmentId;

        //if (confirm("Are you sure you want to update ?")) {
        //    location.href = "/Patient/patient_Registration?id=" + DepartmentId;
        //}
    }
    $(".submitConfirm").click(function () {
        location.href = "/Dignosis/AddDignosis?DignosisID=" + x;
    });

    //function updateDepartment(id) {
    //    if (confirm("Are you sure you want to update ?")) {
    //        location.href = "/Dignosis/AddDignosis?DignosisID=" + id;
    //    }
    //}
    var dl;
    function deleteDignosis(UserId) {
        $('.DmodalMsg').text('Are you sure to delete ?');
        $('.DsubmitConfirm').css('display', 'block');
        $('#DSubmitModal').modal("show");
        dl = UserId;
    }

    $(".DsubmitConfirm").click(function () {
        $.ajax({
            url: "/Dignosis/DeleteDignosis?DignosisID=" + dl,
            type: "POST",
            dataType: "json",
            contentType: "application/json;charset=UTF-8",
            success: function (data) {
                if (data == "3") {
                    $('.modalMsg').text('');
                    $('#DSubmitModal').modal("hide");
                    $('.msgsuccess').text('Data Deleted successfully.');
                    $('#SuccessModal').modal('show');
                    /* window.location.href = "/RegistrationUser/GetAllUsers";*/
                }


            },
            error: function (error) {
                jsonValue = jQuery.parseJSON(error.responseText);
                bootbox.alert("Error : " + jsonValue);
            }
        });

    });
    //function deleteDignosis(DignosisID) {
    //    if (confirm("Are you sure you want to delete ?")) {
    //        $.ajax({
    //            url: "/Dignosis/DeleteDignosis?DignosisID=" + DignosisID,
    //            type: "POST",
    //            dataType: "json",
    //            contentType: "application/json;charset=UTF-8",
    //            success: function (data) {
    //                if (data == "3") {
    //                    alert("Doctor Deleted Successfully");
    //                    window.location.reload();
    //                }
    //                else if (data == "4") {
    //                    alert("Doctor Already In Use!");
    //                    window.location.reload();
    //                }
    //                else { }
    //            },
    //            error: function (error) {
    //                jsonValue = jQuery.parseJSON(error.responseText);
    //                bootbox.alert("Error : " + jsonValue);
    //            }
    //        });
    //    }
    //}
   
    //Pagination
    function getDataTable() {
        $('#tblDignosis').DataTable({
            "searching": true,
            //"bStateSave": true,
            "dom": 'Bfrtip',
            "autoWidth": false,
            "buttons": [
                //{
                //    extend: 'print',
                //    title: 'Manage Block',
                //    exportOptions: {
                //        columns: [0, 1, 2, 3, 4]
                //    },
                //    customize: function (win) { $(win.document.body).css('font-size', '10pt').prepend('<img src="' + origin + '/images/t5-logo-white.png"  style="position:absolute; top:0; left:0;" />'); $(win.document.body).find('table').addClass('compact').css('font-size', 'inherit'); }

                //}
                ,
                {
                    extend: 'pageLength'
                }
            ],
            "lengthMenu": [
                [10, 25, 50, 100, 1000 - 1],
                ['10 rows', '25 rows', '50 rows', '100 rows', '1000 rows', 'Show all']
            ]
        });
    }
</script>